name: Deploy to Azure with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to latest version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to latest version

      - name: Azure Login
        uses: azure/login@v1  # Updated to latest version
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEMP }}

      - name: Initialize Terraform
        run: cd terraform && terraform init

      - name: Plan Terraform
        run: cd terraform && terraform plan

      - name: Apply Terraform
        run: cd terraform && terraform apply -auto-approve
