name: Deploy to Azure with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to latest version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  # Updated   to latest version

      - name: Azure Login
        uses: azure/login@v1  # Updated to latest version
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEMP }}

      - name: Initialize Terraform
        run: cd terraform && terraform init
        
      - name: Validate Terraform
        run: cd terraform && terraform validate
        
      - name: Terraform Import Virtual Network
        run: terraform import azurerm_virtual_network.irmai_vnet "/subscriptions/36448a90-905c-4f48-b1b3-deb171f7c247/resourceGroups/14185-irmai-1-jg5p49/providers/Microsoft.Network/virtualNetworks/irmai-1-jg5p49-vn"

      - name: Terraform Import Network Security Group
        run: terraform import azurerm_network_security_group.irmai_nsg "/subscriptions/36448a90-905c-4f48-b1b3-deb171f7c247/resourceGroups/14185-irmai-1-jg5p49/providers/Microsoft.Network/networkSecurityGroups/irmai-default-nsg"

      - name: Terraform Import AKS Cluster
        run: terraform import azurerm_kubernetes_cluster.irmai_aks "/subscriptions/36448a90-905c-4f48-b1b3-deb171f7c247/resourceGroups/14185-irmai-1-jg5p49/providers/Microsoft.ContainerService/managedClusters/irmai-1-jg5p49"
        

      - name: Plan Terraform
        run: cd terraform && terraform plan -out=tfplan

      - name: Apply Terraform
        run: cd terraform && terraform apply -auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.clientId }}
          ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
          ARM_TENANT_ID: ${{ secrets.tenantId }}
