name: Terraform Deployment

on:
  push:
    branches:
      - main  # Adjust as needed
  pull_request:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

env:
  ARM_USE_OIDC: true  # Enable OIDC authentication
  ARM_SUBSCRIPTION_ID: 36448a90-905c-4f48-b1b3-deb171f7c247

  ARM_TENANT_ID: 38b2a0a6-29a4-4744-ac80-7617428c3bbe

  ARM_CLIENT_ID: 7cc743bd-9d34-40fc-8ff9-b25030f79816

  TF_VERSION: "1.6.0"  # Pin Terraform version
  TF_WORKING_DIR: ./terraform  # Update to match your Terraform directory

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init \
          -backend-config="storage_account_name=irmaitfbackendstorage" \
          -backend-config="container_name=terraform-state" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="resource_group_name=backend-rg"

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -var-file="envs/${{ github.ref_name }}.tfvars" -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
