AZURE_OPENAI_KEY = "FZyDVammGYgt1KJNmnD6zE3klmMoNJlRiGjERiFAG6VT5lnGGRJzJQQJ99ALACYeBjFXJ3w3AAABACOGT8qK"
AZURE_OPENAI_VERSION = "2024-02-15-preview"
AZURE_OPENAI_ENDPOINT = "https://smartcall.openai.azure.com/"

OPENAI_API_KEY="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"